name: ipxbot
description: A home automation notification bot
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.4.2
  matrix:
     git:
       url: https://gitlab.com/famedly/company/frontend/famedlysdk.git
       ref: main
         #    matrix_api_lite: ^-1.1.9
         #  path: ^1.7.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
