name: ipxbot
description: A home automation notification bot
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  matrix_api_lite: ^0.1.9
#  path: ^1.7.0
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.6.2
  build_web_compilers: ^2.12.0
